export enum Panel {
    Adjustments = "adjustments",
    Filmstrip = "filmstrip",
}

export enum Key {
    Enter = "Enter",
    Tab = "Tab",
    Escape = "Escape",
    Question = "?",
    Backslash = "\\",
    BracketLeft = "[",
    BracketRight = "]",
    Minus = "-",
    Plus = "+",
    Equal = "=",
    Arrow_up = "ArrowUp",
    Arrow_down = "ArrowDown",
    Arrow_left = "ArrowLeft",
    Arrow_right = "ArrowRight",
    ArrowUp = "ArrowUp",
    ArrowDown = "ArrowDown",
    ArrowLeft = "ArrowLeft",
    ArrowRight = "ArrowRight",
    Zero = "0",
    One = "1",
    Two = "2",
    Three = "3",
    Four = "4",
    Five = "5",
    Six = "6",
    Seven = "7",
    Eight = "8",
    Nine = "9",
    a = "a",
    b = "b",
    c = "c",
    d = "d",
    e = "e",
    f = "f",
    g = "g",
    h = "h",
    i = "i",
    j = "j",
    k = "k",
    l = "l",
    m = "m",
    n = "n",
    o = "o",
    p = "p",
    q = "q",
    r = "r",
    s = "s",
    t = "t",
    u = "u",
    v = "v",
    w = "w",
    x = "x",
    y = "y",
    z = "z",
    A = "A",
    B = "B",
    C = "C",
    D = "D",
    E = "E",
    F = "F",
    G = "G",
    H = "H",
    I = "I",
    J = "J",
    K = "K",
    L = "L",
    M = "M",
    N = "N",
    O = "O",
    P = "P",
    Q = "Q",
    R = "R",
    S = "S",
    T = "T",
    U = "U",
    V = "V",
    W = "W",
    X = "X",
    Y = "Y",
    Z = "Z",
    Backspace = "Backspace",
    Space = " ",
    PageUp = "PageUp",
    PageDown = "PageDown",
    Home = "Home",
    End = "End",
    F1 = "F1",
    F5 = "F5",
    F11 = "F11",
}

// Keys whose browser default behaviour is suppressed app-wide on keydown
// so it never leaks through (page reload, fullscreen, scroll, space-toggle
// on mouse-focused buttons, …). Tab and Enter are also repurposed app-wide
// but kept inside text inputs; see KeyboardManager.dispatch.
export const SUPPRESSED_DEFAULT_KEYS = new Set<string>([
    Key.F1,
    Key.F5,
    Key.F11,
    Key.PageUp,
    Key.PageDown,
    Key.Home,
    Key.End,
])
